### ISSUE TITLE
Change Header and Title to Reflect Portfolio Information

### ISSUE THREAD

**Issue by kambleaishwarya** [kambleaishwarya/money-management-app#3]
- Update Header: Change the header text to display "Aishwarya Kamble" instead of "Money Management App."
- Update Title Tag: Change the content of the <title> tag to "Aishwarya Kamble" instead of "Money Management Application."
- Add "Download Resume" Button: Add a Download Resume button that allows users to download the resume(at the right side).
[Aishwarya kamble.pdf](https://github.com/user-attachments/files/18269614/Aishwarya.kamble.pdf)

**Comment by MuktaTiwari** [comment]
Hii @kambleaishwarya 
I would like to handle these things, so can I do it?

**Comment by kambleaishwarya** [comment]
Thank you mukta, if you need any help from my side please feel free to ask.

**Comment by MuktaTiwari** [comment]
Hii @kambleaishwarya 
can I add a navbar 
and can you tell me where i can add the  Button to download

**Comment by kambleaishwarya** [comment]
yes sure 
and below the name "Aishwarya Kamble" you can add download cv option on the left or right side 
see on which side it looks good.

**Comment by MuktaTiwari** [comment]
ok sure

**Comment by MuktaTiwari** [comment]
Hii @kambleaishwarya 
i have complete this task 
![Screenshot from 2024-12-29 19-06-04](https://github.com/user-attachments/assets/7fb1a3bd-72b4-4c00-8284-e3300c28e59d)


is this design is fine ??

**Comment by kambleaishwarya** [comment]
yes mukta, good job thank you!

**Comment by MuktaTiwari** [comment]
ok

**Comment by kambleaishwarya** [comment]
mukta i have accepted PR and merge your code.
Thanku for your contribution.

**Comment by kambleaishwarya** [comment]
hii mukta 
resume pdf is not visible i mean it is displaying blank
can you please check and let me know whats the problem.

**Comment by kambleaishwarya** [comment]
im reopening this issue

**Comment by MuktaTiwari** [comment]
checking 
I'll let you know after fixing it.

**Comment by kambleaishwarya** [comment]
ok

**Comment by MuktaTiwari** [comment]
I have resolved the issue.
The file name was not written correctly that why the issue arose.

**Comment by kambleaishwarya** [comment]
okay, good to know that you resolved the issue.
hi mukta, i have accecpted PR.
now im closing this issue.
