### ISSUE TITLE
 Transform "Transactions" into "Projects" Section

### ISSUE THREAD

**Issue by kambleaishwarya** [kambleaishwarya/money-management-app#5]
- Rename the "Transaction History" section to "Projects."
- List personal projects, such as web applications, websites, or any coding projects worked on.
- Each project should have a title of the project, and description.
**Geomitra-One** : This web application is used by the Developer team and their managers. Managers assign new tasks to the developers. It also helps in tracking developers' activity while working on the assigned tasks. Features: 
**User Activity Tracker**: Developed an internal tool allowing managers to monitor tasks in progress, track task completion rates, and assess employee proficiency levels. It improved transparency and productivity tracking across teams. Team **Attendance System:** Built for HR and managers to monitor employee in/out times, manage leaves, track absences and half-days, and generate attendance reports. It streamlined attendance and leave management processes. User Attendance System: Enabled employees to mark their own attendance, enhancing self-management and accuracy while allowing HR to maintain centralized attendance records. 
**Team Performance Tracker:** Provided managers with insights into employee efficiency by tracking task completion times, helping to identify time per task and areas for improvement in team performance. 
Technology Used: Java, Spring Boot, MongoDB, JUnit, HTML, CSS, JavaScript, React.js, Thymeleaf, GitLab

**Comment by Saifkhan-rkp** [comment]
Hey @kambleaishwarya , I would like to work on this issue, can please elaborate and provide CSS styling changes, color codes and UI representation of project section.

**Comment by kambleaishwarya** [comment]
in the existing code there is section of transaction history you have to replace it with projects i have provided you list of proejcts to be added 
and to look portfolio more professional please style with
Background: White.
Text: Dark Gray.
Highlights: Navy Blue and Gold.
if any further information you required please feel free to ask

**Comment by Saifkhan-rkp** [comment]
Hey @kambleaishwarya , I have raised PR #12  having above mention changes accordingly. If anything have to change further, please inform me.

**Comment by kambleaishwarya** [comment]
i have merged your code.
thank you!
