### ISSUE TITLE
Add a "Skills" Section in index.html

### ISSUE THREAD

**Issue by kambleaishwarya** [kambleaishwarya/money-management-app#6]
- Add a "Skills" section to showcase technical skills on the index.html page.
- Create a new section titled "Technical Skills" below the "Projects" section.
- Include the following skills:
Operating Systems: Windows, Linux
Backend: Java, Python
Frontend: HTML/CSS, React.js
Database: MySQL, MongoDB
Frameworks: Spring Boot, Hibernate JPA, React.js, JUnit
Development IDE: STS, Eclipse
Web Server: Apache Tomcat
Architecture: Microservices
APIs: REST API, SOAP API
Tools: GIT, Postman, MySQL Workbench, Swagger

**Comment by keshav-09** [comment]
Hi @kambleaishwarya ,
I would like to work on this task, but I have some doubts regarding the UI:

How should the Technical Skills section be displayed? Should it be in the form of a table or bullet points? Could you please clarify this?

**Comment by kambleaishwarya** [comment]
hello keshav,
Technical skills should be dispalyed in the table format 
like this
Category	                  Skills
Operating Systems     Windows, Linux
Backend	                       Java, Python
Frontend	              HTML/CSS, React.js
Database	             MySQL, MongoDB
Frameworks	             Spring Boot, Hibernate JPA, React.js, JUnit
Development IDE	      STS, Eclipse
Web Server	             Apache Tomcat
Architecture	            Microservices
APIs	                    REST API, SOAP API
Tools	                   GIT, Postman, MySQL Workbench, Swagger

**Comment by keshav-09** [comment]
Thank you @kambleaishwarya  I will do the necessary changes.
And will raise the PR

**Comment by keshav-09** [comment]
@kambleaishwarya  
Create a new section titled "Technical Skills" below the "Projects" section. 
According to this i need to add the technical skills below projects section,but as of now there is no project section so where i need to add this code?

**Comment by kambleaishwarya** [comment]
saif will work on the project section part can you please communicate with him so that after adding the project section  you will start work on skills section
but i think it will create dependecy
so my opinion is you start working and then after adding saif's code you can adjust accordingly

**Comment by keshav-09** [comment]
Okay @kambleaishwarya ,Once saif add the project section code please let me know so that i can make changes in my code

**Comment by kambleaishwarya** [comment]
sure

**Comment by kambleaishwarya** [comment]
hi keshav, i have merged the code of saif.

**Comment by keshav-09** [comment]
Okay @kambleaishwarya

**Comment by keshav-09** [comment]
I have raised the PR. Could you please check it and let me know your feedback?

**Comment by kambleaishwarya** [comment]
yes i have merged your code.
