### ISSUE TITLE
Add a new section titled "Languages" to the page to display a list of spoken languages.

### ISSUE THREAD

**Issue by kambleaishwarya** [kambleaishwarya/money-management-app#7]
- Remove the existing Budget, Savings, and Debt sections and replace them with a new Languages section to display a list of spoken languages.
**Details**
- The Languages section should include the following languages with their corresponding fluency levels:
English
Marathi
Hindi
- Place this section appropriately within the page layout.

**Comment by shubham-ghaturle01** [comment]
Hi @kambleaishwarya ,

I would like to remove the existing Budget, Savings, and Debt sections and replace them with a new "Languages" section displaying the following languages:

English
Marathi
Hindi
Can I go ahead and implement these changes? Please let me know if you have any further instructions!

**Comment by kambleaishwarya** [comment]
yes sure, shubham please go ahead. let me know if any help you required

**Comment by kambleaishwarya** [comment]
Hi Shubham, I see that you have committed the code and raised the PR. 
I am merging this code and closing the issue.
