### ISSUE TITLE
Add Contact Information and Social Media Links also update footer section.

### ISSUE THREAD

**Issue by kambleaishwarya** [kambleaishwarya/money-management-app#8]
- Add a new section titled "Contact Me" to the page to display personal contact information.
**Details**
- The new "Contact Me" section should include the following fields:

Phone: +91 9604387723
Email: aishwaryakamble925@gmail.com
Social Network: LinkedIn  [linkedin.com/in/kambleaishwarya](https://www.linkedin.com/in/kambleaishwarya)
- Ensure that the LinkedIn link is clickable and redirects to the correct LinkedIn profile when clicked.
Address: Nagpur, 440024
- Place this new section appropriately within the page layout, ensuring it fits well with the existing structure.
- replace footer section with this information
"2024 Aishwarya Kamble. All rights reserved"

**Comment by MuktaTiwari** [comment]
Hii @kambleaishwarya 
I want to handle these issues, so I can start working on them if you permit.

**Comment by kambleaishwarya** [comment]
yes sure mukta.
if any help required please feel free to ask.

**Comment by MuktaTiwari** [comment]
I have done with my work and sent you the PR

**Comment by kambleaishwarya** [comment]
hii mukta  i have merged your code 
im closing this issue.
